# Generated by Django 4.0.5 on 2022-07-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=225)),
                ('cost', models.IntegerField()),
                ('full_description', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name_plural': 'Courses',
                'ordering': ['title'],
            },
        ),
    ]
