# Generated by Django 4.0.5 on 2022-07-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=225, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_description',
            field=models.TextField(max_length=3000, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
